### ISSUE TITLE
KDE 21 Missing packages

### ISSUE THREAD

**Issue by jimkp** [kororaproject/kp#55]
The following packages are not in the 21 KDE beta iso when compared to 20.

okular
ktimetracker
kjots
kalarm

calibre is there but lrfviewer and ebook-viewer don't appear in the graphics menu and are supposed to be provided by calibre. Must be some change to the package

interestingly korora-welcome no longer appears on the menu

Marble was a requirement of digikam but is no longer required. To continue including it we need to add it.

**Comment by csmart** [comment]
Missing apps added to ks.

Korora Welcome shows for me, but it's called just "Welcome" now, however it doesn't have an icon. I think that's because it's included in the korora-icon-theme which kde doesn't use. We need to ship that icon with the app.

**Comment by csmart** [comment]
/usr/share/applications/calibre-ebook-viewer.desktop

has nodisplay=true set so that's why it doesn't come it. I assume there's a reason for that, maybe it's only meant to work when you open a file?

**Comment by csmart** [comment]
I don't think we need marble.

**Comment by csmart** [comment]
korora-welcome-21.6-1 pushed to testing repo, if you want to test it to make sure that it has the icon in kde and that it still all works :-)

**Comment by csmart** [comment]
I've removed kdiff3 too, it was there because of backintime, iirc

**Comment by jimkp** [comment]
kdiff3 was there for krusader,

personally like marble but don't think it is used by many people, one of kde's hidden gems

**Comment by csmart** [comment]
ahh ok, that's why. In that case I'll add it back - kdiff3 or kompare?

I'll also add some more archiving utils that krusader seems to want, that will be useful for others
arj
lha
unace
unrar

Not sure about rar yet.

**Comment by jimkp** [comment]
we've always used kdiff3, it can used either. Don't know if kompare offers any additional features

**Comment by jimkp** [comment]
closing as the missing applications have been added
