### ISSUE TITLE
Google Chrome crash

### ISSUE THREAD

**Issue by mustafa-muhammad** [kororaproject/kp#56]
Hi, I am testing Korora 21, I am getting error from ABRT for Google chrome, "google-chrome-stable quit unexpectedly", I can provide more trace at request.

**Comment by firnsy** [comment]
I too use google-chrome-stable exclusively but have had no ABRT reported crashes to date. Can you please provide a pastebin of the full report you getting. And any extensions you have enabled.

**Comment by mustafa-muhammad** [comment]
These informations are from the report ( I put some general info and the core backtrace):

chrome killed by SIGSEGV
/proc/self/exe --type=gpu-process --channel=7653.0.1129089419 --enable-crash-reporter=F233DFAB-6C6C-4253-9366-5387653B9A05 --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,11,15,38 --disable-accelerated-video-decode --gpu-vendor-id=0x8086 --gpu-device-id=0x0126 --gpu-driver-vendor --gpu-driver-version --enable-crash-reporter=F233DFAB-6C6C-4253-9366-5387653B9A05

core_backtrace
{   "signal": 11
,   "executable": "/opt/google/chrome/chrome"
,   "stacktrace":
      [ {   "crash_thread": true
        ,   "frames":
              [ {   "address": 139997716487871
                ,   "build_id": "41d7b1539baa22996d9338f5b89c8095be408aed"
                ,   "build_id_offset": 3608255
                ,   "function_name": "brw_workaround_depthstencil_alignment"
                ,   "file_name": "/usr/lib64/dri/i965_dri.so"
                }
              , {   "address": 139997716090128
                ,   "build_id": "41d7b1539baa22996d9338f5b89c8095be408aed"
                ,   "build_id_offset": 3210512
                ,   "function_name": "brw_clear"
                ,   "file_name": "/usr/lib64/dri/i965_dri.so"
                }
              , {   "address": 139998144797218
                ,   "build_id": "c07a3377dcfb37c0c9c873d4460a3f2cfa08bd02"
                ,   "build_id_offset": 66267682
                ,   "file_name": "/opt/google/chrome/chrome"
                } ]
        }
      , {   "frames":
              [ {   "address": 139998001789241
                ,   "build_id": "1bf31aa5658439b345305715922edf83126ce4bc"
                ,   "build_id_offset": 51513
                ,   "function_name": "pthread_cond_timedwait@@GLIBC_2.3.2"
                ,   "file_name": "/lib64/libpthread.so.0"
                }
              , {   "address": 139998094606579
                ,   "build_id": "c07a3377dcfb37c0c9c873d4460a3f2cfa08bd02"
                ,   "build_id_offset": 16077043
                ,   "file_name": "/opt/google/chrome/chrome"
                } ]
        }
      , {   "frames":
              [ {   "address": 139997974416771
                ,   "build_id": "b9debd8d4a1d247dcbcb4b6675f1567c113fcf0e"
                ,   "build_id_offset": 1052035
                ,   "function_name": "epoll_wait"
                ,   "file_name": "/lib64/libc.so.6"
                }
              , {   "address": 139998094632360
                ,   "build_id": "c07a3377dcfb37c0c9c873d4460a3f2cfa08bd02"
                ,   "build_id_offset": 16102824
                ,   "file_name": "/opt/google/chrome/chrome"
                } ]
        } ]
}

**Comment by mustafa-muhammad** [comment]
Previously I install google-chrome-unstable then removed it and installed google-chrome-stable, now Chrome has no icon and this problem happens.

**Comment by csmart** [comment]
Only thing I can suggest is deleting/moving the chrome profile as that was created/updated with the unstable version, and trying again so you get a clean profile with the stable version. Unfortunately Google Chrome is proprietary and we can't do much to change it..

```bash
mv ~/.config/google-chrome{,-unstable}/
```

**Comment by mustafa-muhammad** [comment]
I already did that by didn't solve the problem, now I'll try removing the whole package and try again

**Comment by mustafa-muhammad** [comment]
Removed google-chrome-stable and reinstalled, still happening, removed profile, still happening.

**Comment by csmart** [comment]
can you create a new user and try there? I think this must be a user problem as chrome ships all its libraries statically, so I don't think the host os is going to affect much..

**Comment by mustafa-muhammad** [comment]
I created a new user, same problem.

**Comment by csmart** [comment]
ok, weird.. wonder if it's graphics driver related. Did you install a proprietary driver?

Also, do you have packages from other repos? What repos do you have enabled?

```bash
sudo yum repolist
```

Can you do a repo-sync to ensure you only have packages from relevant repos?

```bash
sudo yum distro-sync
```

**Comment by mustafa-muhammad** [comment]
No, no proprietary drivers, no other packages.
I always do distro-sync, and my repos are:
Loaded plugins: etckeeper, langpacks, priorities, refresh-updatesd, versionlock
34 packages excluded due to repository priority protections
repo id                                        repo name                                               status
!adobe/x86_64                                  Adobe                                                         1+1
fedora/21/x86_64                               Fedora 21 - x86_64                                      42,789+27
!google-chrome                                 google-chrome                                                   3
!korora                                        Korora 21 - x86_64                                             97
rpmfusion-free/21/x86_64                       RPM Fusion for Fedora 21 - Free                               470
!rpmfusion-free-updates/21/x86_64              RPM Fusion for Fedora 21 - Free - Updates                      66
rpmfusion-nonfree/21/x86_64                    RPM Fusion for Fedora 21 - Nonfree                            178
!rpmfusion-nonfree-updates/21/x86_64           RPM Fusion for Fedora 21 - Nonfree - Updates                   36
!updates/21/x86_64                             Fedora 21 - x86_64 - Updates                              5,432+7
repolist: 49,072

If this only happens with me with this beta, its OK, I might try fresh installation.

**Comment by mustafa-muhammad** [comment]
I erased Korora and installed from scratch, same problem!
Then I installed Fedora, this does not happen in Fedora.

Regards

**Comment by csmart** [comment]
Really! Interesting.. I can't think of any reason, all the libs, including those in the stacktrace, are the same. Did you install all available updates in Fedora 21?

Only possible thing I can think of, and I'd have thought it would have shown its ugly head by now if it was, is that the Korora media is corrupt? Can you please do a verify and boot option from the troubleshooting menu?

**Comment by mustafa-muhammad** [comment]
I already checked sha256sum of the iso, "Verify and Boot" shows "PASS" (by the way it is the default, not in the Troubleshooting), and reinstalled for the third time.
I thought it is an SELinux issue, and indeed, I used:
#setenforce 0
and the error no longer happen.
After setenforce 1, it still not happening!
In the logs I have:
Jan 11 11:30:06 localhost.localdomain kernel: chrome[28857]: segfault at 1f8 ip 00007f093452a13f sp 00007fff18ede090 error 4 in i965_dri.so[7f09341b9000+53e000]

**Comment by mustafa-muhammad** [comment]
Probably not SELinux, I disabled it and still happen, maybe Intel driver i965_dri.so?

**Comment by csmart** [comment]
I'm using the same driver.. my GPU is:

```bash
[20:29] chris@x220 ~ $ lspci |grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
```
