### ISSUE TITLE
Two finger scrolling not working properly

### ISSUE THREAD

**Issue by mustafa-muhammad** [kororaproject/kp#57]
Two finger scrolling didn't work for me, so I went to touchpad configuration, and it was enabled and working on that window, I've been working on Korora for about a week and it sometimes work, but most of the time not.

**Comment by firnsy** [comment]
What is your touchpad? Which DE? I can't reproduce on Gnome.

**Comment by csmart** [comment]
I think this is related to #58

**Comment by mustafa-muhammad** [comment]
Yes, it is related, the fix you gave me for that:
rm ~/.config/autostart/syndaemon.desktop
fixed this issue too.

**Comment by csmart** [comment]
Fixed with #58
