### ISSUE TITLE
Tapping by click activated but not working

### ISSUE THREAD

**Issue by mustafa-muhammad** [kororaproject/kp#58]
"Mouse click emulation" is enabled but not working.

**Comment by csmart** [comment]
Thanks for the report, can you tell me which desktop are you using? Thanks!

**Comment by mustafa-muhammad** [comment]
Welcome, I use KDE, maybe something wrong with the KCM, I have another issue with the touchpad (both not exist inf Fedora)

**Comment by csmart** [comment]
In KDE we run syndaemon, can you please try to remove this and log out and back in and check your settings, then let me know if it solves your problem?

```bash
rm ~/.config/autostart/syndaemon.desktop
```

**Comment by mustafa-muhammad** [comment]
This solved the problem for me, until now everything works fine, tappint and scrolling, thanks.

**Comment by csmart** [comment]
@mustafa-muhammad Great, I'll add this fix for Korora 21, thanks for helping to make it better!

**Comment by mustafa-muhammad** [comment]
Thank you, by the way there are some really old issues here, I recommend closing the issues that affect EOLed versions, e.g. one issue talks about F18.

**Comment by csmart** [comment]
@mustafa-muhammad great, thanks.
