### ISSUE TITLE
Apps closed on reboot doesn't run on next boot

### ISSUE THREAD

**Issue by mustafa-muhammad** [kororaproject/kp#59]
In most distributions I use, including Fedora, apps that was running before reboot starts automatically on next login ( I think this is the default for KDE), but not in Korora.

**Comment by csmart** [comment]
Thanks for the report! This is by design as I think most users are happy to re-open whatever apps they use after a log in - most users will suspend otherwise which means the same apps are still running. I'll ask our KDE guy though for his thoughts..

**Comment by jimkp** [comment]
KDE system settings - Startup and Shutdown - Session Management is set to Restore Manually Saved Session, change to Restore Previous Session will give you the desired behaviour.

**Comment by firnsy** [comment]
Agreed with @csmart, restarting means restoring to a known clean state Enabling by default would require even more work from the user to obtain a clean start. I would be a strong -1 for such a change.

**Comment by csmart** [comment]
Closing as this is by design. Thanks!

**Comment by mustafa-muhammad** [comment]
I wasn't sure if this was a design decision, both behaviours are fine for me, thank you all.
