### ISSUE TITLE
Gnome 23 Beta Issues reported on Engage

### ISSUE THREAD

**Issue by jimkp** [kororaproject/kp#67]
See https://kororaproject.org/support/engage/question/kora23-gnome-beta-wallpaper-duplicate-entry-1

Background  /usr/share/backgrounds/gnome/adwaita-timed.xml appears twice in wallpaper selection screen

Removable drive menu doesn't work

Launch New Instance behaves inconsistently, see Engage for testing results

**Comment by csmart** [comment]
OK, so the wallpaper one I'm not going to bother about, it's too small a fish to fry. Someone else can have a crack if the want, see engage for my analysis.

Taskbar we don't want in GNOME, no-one should be minimising apps and we should use the overview and desktops to switch. Perhaps we need a video on how to use GNOME.

Removable menu working as expected - only shows up when you plug in removable media.

Launch New Instance extension seem flakey, but we should give it to @firnsy to look at or submit bug report upstream.

Once we decide on launch new instance, we can close this bug.

**Comment by DarkEra** [comment]
No video(s) needed on how to use Gnome 3. If i remember correct ships 3 videos by default under Help -> Getting started with Gnome: 1. Launch applications. 2. Switch tasks. 3. Respond to messages.

Help also includes a lot more info.

**Comment by csmart** [comment]
maybe another @firnsy one, re GNOME launch new instance?

**Comment by firnsy** [comment]
I commented on "Launch new instance" yesterday at
https://kororaproject.org/support/engage/question/kora23-gnome-beta-wallpaper-duplicate-entry-1

The dash-to-dock extension has support in it, and it works for me for on the Terminal.
