### ISSUE TITLE
Theming issue KDE Plasma 5 K23

### ISSUE THREAD

**Issue by DarkEra** [kororaproject/kp#69]
I installed K23 KDE Plasma 5 Beta today on the Lenovo. After updating the OS it seems there are issues with the Korora theme. The blue color seems to be a bit off. See the attached picture:

![themeing_issue](https://cloud.githubusercontent.com/assets/6264656/11171498/ee96d572-8bf1-11e5-8708-d42ab4b7f11b.png)

I experienced no issues with the other themes included after i switch to them to check if the issue occurred there too. Here's how it should look like:

![themeing_issue2](https://cloud.githubusercontent.com/assets/6264656/11171601/89313166-8bf4-11e5-84c4-77ccaebc148d.png)

**Comment by csmart** [comment]
@DarkEra thanks, if you change theme to fedora's one, does it have the same problem?

**Comment by DarkEra** [comment]
@csmart If i change the theme to Fedora's one, it doesn't have the problem. I tried all other themes that are included by default, no issues so far with those. It only seems to happen when our theme is used.

**Comment by csmart** [comment]
@DarkEra ok, thanks.. guess I have more work to do.

**Comment by DarkEra** [comment]
@csmart I noticed there are more glitches when moving the mouse cursor over it, open the menu or another application. This is what happens when i use the Icons-only Task Manager alternative version:

One app open and moving the mouse cursor over it:
![themeing_issue3](https://cloud.githubusercontent.com/assets/6264656/11181300/48ff0cea-8c61-11e5-81ba-42d5fcbf5e6a.png)

The Menu or another application open:
![themeing_issue4](https://cloud.githubusercontent.com/assets/6264656/11181312/5e219d54-8c61-11e5-9084-2feda647258d.png)
