### ISSUE TITLE
DownThemAll not working for me

### ISSUE THREAD

**Issue by mustafa1024m** [kororaproject/kp#70]
I am testing Korora 23 beta, I use DownThemAll, but here it is not working, even after removing the profile directory (.mozilla) and starting fresh.
You can try by opening the DTA Manager, all I get is a window with "Loading"

**Comment by mustafa-muhammad** [comment]
After removing the package mozilla-downthemall and installing from the official addons, it works.
So the problem is probably in the packaged version.

**Comment by csmart** [comment]
Thanks for reporting this, will do some more testing. Cheers.
