### ISSUE TITLE
Alacarte doesn't work in Gnome

### ISSUE THREAD

**Issue by GizmoCodes** [kororaproject/kp#71]
On Korora 23 (And 22, I think), Alacarte dosn't seem to work. After installation via `dnf install alacarte`, it seems that making modifications to the menu doesn't take effect. For example, I tried to remove the LiveUSB Creator, but removing it from Alacarte didn't do anything.

Perhaps, in the next K23 update for Gnome, a patched/working version of Alacarte could be bundled with it?

**Comment by csmart** [comment]
I don't even know if there is one any more.. I think it's all .desktop file manipulation in your ~/.local/share/applications/ dir

**Comment by GizmoCodes** [comment]
Yeah, I know I could just modify the .desktop files, but I was just thinking for conveniences sake; since some people new to Linux may not know what to do.

**Comment by csmart** [comment]
yeah agreed.. I'm just not sure there is anything that works?

**Comment by GizmoCodes** [comment]
True; I'm not too familiar with Alacarte, but I believe its open-sourced, so maybe someone from the Korora community might fork a working version, or make a .desktop file manager?

**Comment by csmart** [comment]
With GNOME 3 there's probably less need for a menu manager as you search for apps rather than click through menus. It might be good to have, but we're so busy with all the other things we have to get working.. appreciate the suggestion though! We'll keep it on the back burner.

**Comment by GizmoCodes** [comment]
Alright, thanks anyways!
