### ISSUE TITLE
Adding copr repository failure K22

### ISSUE THREAD

**Issue by kujaw** [kororaproject/kp#72]
Here's the log:

> sudo dnf copr enable eischmann/purple-telegram 
> 
> You are about to enable a Copr repository. Please note that this
> repository is not part of the main Fedora distribution, and quality
> may vary.
> 
> The Fedora Project does not exercise any power over the contents of
> this repository beyond the rules outlined in the Copr FAQ at
> <https://fedorahosted.org/copr/wiki/UserDocs#WhatIcanbuildinCopr>, and
> packages are not held to any quality or security level.
> 
> Please do not file bug reports about these packages in Fedora
> Bugzilla. In case of problems, contact the owner of this repository.
> 
> Do you want to continue? [y/N]: y
> Error: This repository does not have any builds yet so you cannot enable it now.

This repository has builds and works when I manually add it. But using the terminal it's impossible to add the repo.

**Comment by csmart** [comment]
Thanks for the report. The error says that there are no packages in the repo, that's why it can't add it. According to the copr, there are no packages in i386 repo but there are in the x86_64 repo. Are you running 32bit?

**Comment by kujaw** [comment]
Yes, it was 32bit Fedora. Sorry for such late response ..

**Comment by csmart** [comment]
OK, so yes that won't work because there are no 32bit packages available. If the person who creates the repo makes 32bit packages, it will work.
