### ISSUE TITLE
Xfce Beta test Issues for 24

### ISSUE THREAD

**Issue by jimkp** [kororaproject/kp#74]
**DONE** Panel has 2 power manager icons, switch off System Tray Icon in Power Manager

**DONE** No volume icon on panel - add PulseAudio Plugin to panel

**DONE** Replace Openshot with Pitivi (or equivalent)

**DONE** Set WM and Appearance theme to Arc

**DONE** Set Icons to Numix Circle

Add Xfpanel-switch preset for Korora panel

(Desirable improvement) add ksuperkey to Korora repo and configure Super key to open menu

**Comment by csmart** [comment]
some done

**Comment by csmart** [comment]
Done all of them except the xfpanel-switch preset.. which I think we can ship later

**Comment by csmart** [comment]
@jimkp when you have your new iso can you confirm all these are fixed to your satisfaction and then let us know if anything else is broken. thanks!

**Comment by jimkp** [comment]
Pitivi is installed but doesn't run as gst-transcoder is missing, installed and pitivi runs
action needed - add gst-transcoder

Other changes complete

**Comment by csmart** [comment]
I've already added gst-transcoder to the ks - it's not a dep of the rpm cause I'm using upstream's srpm https://github.com/kororaproject/kp-config/commit/7f8471002f19e19c709dae02f6519d28344bfcd8

Others fixed, so closing. Thanks.
