### ISSUE TITLE
Update welcome for 24

### ISSUE THREAD

**Issue by firnsy** [kororaproject/kp#75]
Update welcome utility to show k24 relevant information.

**Comment by jimkp** [comment]
Xfce now includes xfpanel-switch which allows the panel settings to be saved and restored It also includes several alternative panel configs.

(TBC) Ksuperkey has been added to KDE Plasma, Xfce (any others?) to provide the option of creating keyboard shortcuts using the super key while the super key used by itself will open the menu.

The default icon theme in Korora is now the standard Numix Circle. The Korora icon them is no longer needed as our enhancements have been accepted upstream.

**Comment by csmart** [comment]
ksuperkey is done

**Comment by csmart** [comment]
thanks @firnsy kororaproject/kp-korora-welcome@405050f
