### ISSUE TITLE
K24 KDE Early Beta test iso issues

### ISSUE THREAD

**Issue by DarkEra** [kororaproject/kp#77]
- Testing this media results in Pass but doesn't load the desktop after it finished. We have the same   issue on K23 but it got never reported.
- Currently there are three web browsers included on the KDE spin Firefox, Konqueror and Qupzilla. All three apps have the same main purpose, browse the web. So we have to narrow it down to at least two if possible.
- Firefox uses our Ublock Origin mozilla build but it's outdated, it's 1.5.3 while Ublock Origin is on 1.7.X
  (not 100% sure about this one since i don't know if it's our version numbering or ublock origins one)
- **DONE** Include Sound Konverter, the other spins have Sound Converter included.
- **DONE** Include ksuperkey which needs to be added to Startup and Shutdown -> Desktop File
- Two installer icons were showing on the desktop in live mode.
- **DONE** Korora Welcome doesn't show after the desktop is loaded.
- The KDE bootsplash is showing Fedora's background.
- Background is missing on the login screen and the desktop
- The desktop layout is set to Folder View instead of Desktop (which should be the default).
- **CHECK** touch movie.mvk resulted in no default app, so VLC isn't assigned to it. 
- The control buttons in Audacity seem to disappear when hovering over them with the mouse cursor.
- The mouse cursor theme is set to Breeze instead of Adwaita which we used as default in previous releases.
- Set the Desktop Theme to Breeze Dark as default so it's in line with the other spins themewise.

**Comment by csmart** [comment]
I'm not sure that touching movie.mkv will work cause it won't have the appropriate mimetype? This is in the mimeapps.list:
  video/x-matroska=vlc.desktop;vlc.desktop;

So a real matroska file should work. GNOME doesn't have mkv in their mimeapps.list either, so maybe can we check with a real file?
