### ISSUE TITLE
VLC has audio only - no GUI

### ISSUE THREAD

**Issue by ZumaMan** [kororaproject/kp#79]
I have Korora 24 freshly loaded. Also just got the latest updates. When I play a video file using VLC media player, I can hear the audio, but cannot see the anything. The video does not show and also the GUI does not show. When I hit the alt-tab combination, it does not show VLC as being in the list.
$ ps aux | grep vlc
jj        1701  0.4  2.1 1931312 85660 tty2    Sl+  16:17   0:05 /usr/bin/vlc --started-from-file
jj        2744  0.0  0.0 117144   896 pts/0    S+   16:38   0:00 grep --color=auto vlc
I have a dual boot with Ubuntu and VLC works fine with the Ubuntu OS. My previous OS was Fedora 23. I did not have a problem with Fedora 23, but after upgrading to Fedora 24, VLC broke. Thinking my upgrade failed, I deleted my Fedora partition and installed Korora 24 from scratch. Now. same problem.
Thanks

**Comment by csmart** [comment]
Hmm.. if you run it on the command line, do you get any errors that you can paste?

Also, can you run this check to see if you have the following packages installed?

`rpm -q qt5-qtx11extras libxcb xcb-util-keysyms`

**Comment by ZumaMan** [comment]
[18:32 jj ~]$ rpm -q qt5-qtx11extras libxcb xcb-util-keysyms
qt5-qtx11extras-5.6.1-2.fc24.x86_64
libxcb-1.11.1-2.fc24.x86_64
xcb-util-keysyms-0.4.0-3.fc24.x86_64

**Comment by ZumaMan** [comment]
[VLC_Errors.txt](https://github.com/kororaproject/kp/files/568211/VLC_Errors.txt)

First error is: QWidget::setMinimumSize: (/FirstRun) Negative sizes (-491607381,-491607381) are not possible

See attached file for complete error message list.

**Comment by ZumaMan** [comment]
Check out this link: I have exactly the same problem:
http://forums.fedoraforum.org/showthread.php?p=1771736

**Comment by ZumaMan** [comment]
For output from: vlc --file-logging VLCLOG --verbose=2
[vlc-log.txt](https://github.com/kororaproject/kp/files/568234/vlc-log.txt)

**Comment by csmart** [comment]
in vlc-log.txt it seems to be trying to play file:///home/jj/VLCLOG ? But it doesn't exist?

`filesystem error: cannot open file /home/jj/VLCLOG (No such file or directory)`

**Comment by csmart** [comment]
Are you running proprietary nvidia drivers? If so, can you try reverting to nouveau and seeing if the problem does away?

**Comment by ZumaMan** [comment]
See also:
https://forum.videolan.org/viewtopic.php?f=13&t=136151&p=449576#p449576
If I run VLC from the command line and add the option:
vlc filename.mp4 --no-embedded-video
then I get video, but no GUI controls just as they said.

**Comment by ZumaMan** [comment]
I am running whatever video drivers come with the package. This is a clean install with no mods.

**Comment by ZumaMan** [comment]
Here is my video card:
$ lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cedar [Radeon HD 5000/6000/7350/8350 Series]

**Comment by ZumaMan** [comment]
Here is X driver:
$ glxinfo | grep -i vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: X.Org (0x1002)
OpenGL vendor string: X.Org

**Comment by ZumaMan** [comment]
VLC Version:
$ rpm -qa | grep vlc
vlc-3.0.0-0.8.fc24.x86_64
vlc-extras-3.0.0-0.8.fc24.x86_64
vlc-core-3.0.0-0.8.fc24.x86_64

**Comment by csmart** [comment]
OK, interesting, thanks. Are you running in Wayland session?

I can only assume that upstream RPMFusion has broken VLC, but I can't find a bug upstream:
https://bugzilla.rpmfusion.org/buglist.cgi?quicksearch=vlc

Did you try the downgrade as mentioned in the Fedora Forum post?

`dnf downgrade vlc vlc-core`

**Comment by ZumaMan** [comment]
Not yet, I wanted to get as much info as possible first. I am not in any hurry as I dual boot with Ubuntu 16.04 and it works fine with that. 
FYI with Ubuntu I have VLC version 2.2.2 Weathermax
I will give it a try if you can guide me through getting the latest version back so we can continue testing with the broken version.

**Comment by csmart** [comment]
If you downgrade, you can just dnf upgrade again - we keep the older rpms in the repo for a while, but they do get removed. I can also try and build vlc from fedora 25 for fedora 24 and see if that helps.. strange cause it doesn't seem to be affecting many people :-S

**Comment by ZumaMan** [comment]
$ sudo dnf downgrade vlc vlc-core
Last metadata expiration check: 1:30:33 ago on Wed Nov  2 21:45:42 2016.
Error: package vlc-extras-3.0.0-0.8.fc24.x86_64 requires vlc-core(x86-64) = 3.0.0-0.8.fc24, but none of the providers can be installed
(try to add '--allowerasing' to command line to replace conflicting packages)

**Comment by csmart** [comment]
OK, so it's not happy with the dependencies.. I don't have 24 handy, can you add --allowerasing and see what happens? Failing that we can remove vlc and install the specific version:

`sudo dnf erase vlc
sudo dnf install vlc-3.0.0-0.1.fc24.x86_64 vlc-core-3.0.0-0.1.fc24.x86_64`

**Comment by jimkp** [comment]
Try dnf downgrade vlc*
That command worked for me on Cinnamon

**Comment by csmart** [comment]
@ZumaMan also, can you try to move your existing vlc config out of the way so that you get a fresh one, and see if it helps?

```
mv ~/.config/vlc{,-moved}
vlc filename.mp4

```
Can you also try creating a new user, logging in as that new user and running vlc?

**Comment by ZumaMan** [comment]
Here is a quote from: https://forum.videolan.org/viewtopic.php?t=134319

"So I asked the RPMFusion guys why they included bleeding-edge 3.0.0 VLC in their repository: https://bugzilla.rpmfusion.org/show_bug.cgi?id=4185
It was done so because the packager of ffmpeg (also from RPMFusion) bundled ffmpeg-3.x.x, which VLC 2.2.4 doesn't build with. Given that ffpmeg 3.x.x has been out for some time, I can't blame RPMFusion packager's decision to go for ffmpeg 3.x.x for Fedora 24.

What I'd like to know, however, is whether VLC 2.2.4 not building with ffmpeg 3.x.x is genuine incompatibility or some artificial version limit set forth within the make configure script. If VLC 2.2.x can be patched to work with ffpmeg 3.x.x, we will have a path toward RPMFusion providing VLC 2.2.x instead of 3.0.0."

So it looks like Fedora/Korora 24 is inherently broken as far as VLC is concerned. The only reason I chose Korora over Fedora 24 is because it was supposed to come prepackaged with a working version of VLC. So my only resolve is to go back to a Ubuntu based distro which does not seem to have such problems. Thank you csmart for all your help.

**Comment by ZumaMan** [comment]
$ sudo dnf downgrade vlc vlc-core --allowerasing
[sudo] password for jj: 
Last metadata expiration check: 2:12:47 ago on Mon Nov  7 18:12:44 2016.
Dependencies resolved.
================================================================================
 Package          Arch         Version               Repository            Size
================================================================================
Downgrading:
 vlc              x86_64       3.0.0-0.1.fc24        rpmfusion-free       1.8 M
 vlc-core         x86_64       3.0.0-0.1.fc24        rpmfusion-free       7.9 M
 vlc-extras       x86_64       3.0.0-0.1.fc24        rpmfusion-free        62 k

Transaction Summary
================================================================================
Downgrade  3 Packages

Total download size: 9.8 M
Is this ok [y/N]: 
...
...
Downgraded:
  vlc.x86_64 3.0.0-0.1.fc24               vlc-core.x86_64 3.0.0-0.1.fc24       
  vlc-extras.x86_64 3.0.0-0.1.fc24       


Before:
$ rpm -qa | grep vlc
vlc-3.0.0-0.8.fc24.x86_64
vlc-extras-3.0.0-0.8.fc24.x86_64
vlc-core-3.0.0-0.8.fc24.x86_64

After:
$ rpm -qa | grep vlc
vlc-extras-3.0.0-0.1.fc24.x86_64
vlc-core-3.0.0-0.1.fc24.x86_64
vlc-3.0.0-0.1.fc24.x86_64

**Comment by ZumaMan** [comment]
VLC now works as I expect.

**Comment by ZumaMan** [comment]
@csmart: Sorry, I downgraded before I read your next suggestion. At least now we know one thing that works and one that does not. For your other suggestion:

mv ~/.config/vlc{,-moved}
vlc filename.mp4

I presume you want me to do that with the latest version of VLC. Going back to latest VLC version:

$ sudo dnf install vlc
[sudo] password for jj: 
Last metadata expiration check: 2:32:17 ago on Mon Nov  7 18:12:44 2016.
Package vlc-3.0.0-0.1.fc24.x86_64 is already installed, skipping.
Dependencies resolved.
================================================================================
 Package        Arch       Version             Repository                  Size
================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 vlc            x86_64     3.0.0-0.8.fc24      rpmfusion-free-updates     1.8 M
 vlc-core       x86_64     3.0.0-0.8.fc24      rpmfusion-free-updates     7.8 M
 vlc-extras     x86_64     3.0.0-0.8.fc24      rpmfusion-free-updates      62 k

Transaction Summary
================================================================================
Skip  3 Packages

Nothing to do.
Complete!
[20:45 jj ~]$ sudo dnf install vlc --best --allowerasing
Last metadata expiration check: 2:33:08 ago on Mon Nov  7 18:12:44 2016.
Package vlc-3.0.0-0.1.fc24.x86_64 is already installed, skipping.
Dependencies resolved.
================================================================================
 Package        Arch       Version             Repository                  Size
================================================================================
Upgrading:
 vlc            x86_64     3.0.0-0.8.fc24      rpmfusion-free-updates     1.8 M
 vlc-core       x86_64     3.0.0-0.8.fc24      rpmfusion-free-updates     7.8 M
 vlc-extras     x86_64     3.0.0-0.8.fc24      rpmfusion-free-updates      62 k

Transaction Summary
================================================================================
Upgrade  3 Packages

Total download size: 9.7 M
Is this ok [y/N]:
...
...
Upgraded:
  vlc.x86_64 3.0.0-0.8.fc24               vlc-core.x86_64 3.0.0-0.8.fc24       
  vlc-extras.x86_64 3.0.0-0.8.fc24

**Comment by ZumaMan** [comment]
OK I again have the broken version of VLC:

$ rpm -qa | grep vlc
vlc-core-3.0.0-0.8.fc24.x86_64
vlc-extras-3.0.0-0.8.fc24.x86_64
vlc-3.0.0-0.8.fc24.x86_64

**Comment by csmart** [comment]
OK, so .8 is broken.

Can you downgrade again and then lock it?

`sudo dnf versionlock add vlc`

That should stop you from getting the newer broken version.

What's interesting is that I've asked everyone else running k24 and no-one has the vlc issue.. so it is strange.

**Comment by ZumaMan** [comment]
$ mv ~/.config/vlc{,-moved}

vlc folder gets renamed as vlc-moved:

 ~/.config]$ ls -d v*
vlc-moved

Now running a mp4 file...

$ vlc RW10.mp4
VLC media player 3.0.0-git Vetinari (revision 2.2.0-git-8754-g1c89583)
[00005573bddec1c8] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
QWidget::setMinimumSize: (/FirstRun) Negative sizes (-491607381,-491607381) are not possible
...

This did not help. Still have audio only with no GUI. Killing the VLC process:
$ killall vlc

But I did get a new vlc config directory:
$ ls -d  ~/.config/v*
/home/jj/.config/vlc  /home/jj/.config/vlc-moved

I'll go back now and downgrade and lock.

$ sudo dnf downgrade vlc vlc-core --allowerasing
$ sudo dnf versionlock add vlc
Last metadata expiration check: 0:12:29 ago on Mon Nov  7 21:14:09 2016.
Adding versionlock on: vlc-0:3.0.0-0.1.fc24.*

**Comment by csmart** [comment]
ok that looks good, and I assume it works again now? If you try to upgrade vlc it shouldn't find the newer version:

`dnf upgrade vlc `

**Comment by ZumaMan** [comment]
So, for now it looks like the workaround for anyone with this problem is the following:

$ sudo dnf downgrade vlc vlc-core --allowerasing
$ sudo dnf versionlock add vlc

However this is a temporary fix since I still want to get the upgrades as they come in. Remember, also that many people on the Fedora forums are reporting this issue for version 24 and the same VLC version, so it looks like some joint effort is needed to solve the problem- maybe as far back as fixing the QT version. I'll check back here from time to time to see if there are other ideas to try. Most likely all the people with problems have some similar configurations on their computers. 

I don't mind helping with this issue. If you want, I can compile the source with a couple different versions of the compiler/QT version. I don't exactly know the history behind what changed to cause the failure on some systems, but if someone can research this and step me through how to test different versions of interest we can use my computer as a test platform.

**Comment by jimkp** [comment]
There is a [RPMFusion bug](https://bugzilla.rpmfusion.org/show_bug.cgi?id=4306) if you would like to help

**Comment by csmart** [comment]
Is that the same problem he's facing though?

**Comment by ZumaMan** [comment]
I don't recall seeing any xcb error messages.

**Comment by jimkp** [comment]
Quote from above "Check out this link: I have exactly the same problem:
http://forums.fedoraforum.org/showthread.php?p=1771736"
It is full of xcb errors

**Comment by ZumaMan** [comment]
Here is my output in terminal when it is failing:

$ vlc RW10.mp4
VLC media player 3.0.0-git Vetinari (revision 2.2.0-git-8754-g1c89583)
[00005573bddec1c8] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
QWidget::setMinimumSize: (/FirstRun) Negative sizes (-491607381,-491607381) are not possible
QWidget::setMinimumSize: (/QStatusBar) The largest allowed size is (16777215,16777215)
QWidget::setMaximumSize: (/QStatusBar) The largest allowed size is (16777215,16777215)
QWidget::setMinimumSize: (/FirstRun) Negative sizes (-491607381,-491607381) are not possible
QXcbConnection: XCB error: 3 (BadWindow), sequence: 422, resource id: 25165828, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 423, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 424, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 425, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 427, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 428, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 429, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 433, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 437, resource id: 25165828, major code: 2 (ChangeWindowAttributes), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 438, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 439, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 440, resource id: 25165828, major code: 20 (GetProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 444, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 445, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0

**Comment by ZumaMan** [comment]
@jimkp So, yes, you are correct in that.

**Comment by ZumaMan** [comment]
But I don't get:

VLC media player 3.0.0-git Vetinari (revision 2.2.0-git-8754-g1c89583)
[000055868f4a81c8] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
This application failed to start because it could not find or load the Qt platform plugin "xcb"

Could these two problems be related? I'm not ready to start stepping through code, but I don't mind doing a couple of compiles with different variables to see what changes.

**Comment by jimkp** [comment]
The strange thing is that only some people are affected. It works for the majority of users. If there was a way to find the common factor the solution would probably be simple.

**Comment by csmart** [comment]
Yeah makes me wonder if it's a combination of graphics drivers or something.. or running on wayland, or something..

**Comment by ZumaMan** [comment]
Looking at the ChangeLog from: 
https://www.rpmfind.net/linux/RPM/rpmfusion/free/fedora/updates/24/x86_64/v/vlc-3.0.0-0.8.fc24.x86_64.html

Note that version 3.0.0-0.1 (which works) uses QT version 5. So I would say that this is not a QT problem. However, version 3.0.0-0.4 says:
  - Rebuilt for ffmpeg-3.1.1

Now currently on my working version I have:
$ ffmpeg -version | grep "version"
ffmpeg version 3.0.3 Copyright (c) 2000-2016 the FFmpeg developers

So I think a reasonable probability is that the ffmpeg version is at fault.

When I downgraded I went from 3.0.0-0.8 to version 3.0.0-0.1. How can I try the intermediate versions between 0.1 and 0.8 to see exactly where it breaks?


Changelog

* Thu Sep 08 2016 Nicolas Chauvet <kwizart@gmail.com> - 3.0.0-0.8
  - Re-enable bootstrap
* Fri Sep 02 2016 Nicolas Chauvet <kwizart@gmail.com> - 3.0.0-0.7
  - Bump to 20160901 nightly
  - Fix plugins.dat path - rfbz#4184
* Thu Aug 18 2016 SÃ©rgio Basto <sergio@serjux.com> - 3.0.0-0.6
  - Clean spec, Vascom patches series, rfbz #4196, add license tag
* Thu Aug 04 2016 Leigh Scott <leigh123linux@googlemail.com> - 3.0.0-0.5
  - Remove -f from vlc-cache-gen scriptlets rfbz#4167
* Sat Jul 30 2016 Julian Sikorski <belegdol@fedoraproject.org> - 3.0.0-0.4
  - Rebuilt for ffmpeg-3.1.1
* Fri Jul 29 2016 Nicolas Chauvet <kwizart@gmail.com> - 3.0.0-0.3
  - Update to today snapshoot
* Fri Jul 01 2016 Nicolas Chauvet <kwizart@gmail.com> - 3.0.0-0.2
  - Update to today snapshot
* Tue Jun 14 2016 Nicolas Chauvet <kwizart@gmail.com> - 3.0.0-0.1
  - Update to 3.0.0 - snapshot 20160614
  - Switch to qt5
  - Update Build Dependencies

**Comment by ZumaMan** [comment]
By the way, with version 3.0.0-0.8 I can play videos via 
$ rvlc
> add filename.mp4
> volume 150
So, really, the only thing broken in 3.0.0-0.8 is the menu items in the GUI.

**Comment by ZumaMan** [comment]
$ sudo dnf install vlc.x86_64 3.0.0-0.4.fc24  
Last metadata expiration check: 2:47:48 ago on Thu Nov 10 21:45:16 2016.
Package vlc-3.0.0-0.1.fc24.x86_64 is already installed, skipping.
No package 3.0.0-0.4.fc24 available.
Error: Unable to find a match.

Also:
]$ dnf --showduplicates list vlc
Last metadata expiration check: 0:15:46 ago on Fri Nov 11 00:19:02 2016.
Installed Packages
vlc.x86_64                 3.0.0-0.1.fc24                 @rpmfusion-free       
Available Packages
vlc.x86_64                 3.0.0-0.1.fc24                 @rpmfusion-free       
vlc.x86_64                 3.0.0-0.1.fc24                 rpmfusion-free        
vlc.x86_64                 3.0.0-0.8.fc24                 rpmfusion-free-updates

Apparently different versions were compiled, but not released?
