### ISSUE TITLE
mozilla-ublock-origin needs to be updated

### ISSUE THREAD

**Issue by DarkEra** [kororaproject/kp#86]
The mozilla-ublock-origin package is deprecated and needs to be updated for Korora 25. The current uBlock Origin stable release is at 1.13, if i remember correct we still ship 1.9.x.

May be a good thing to keep a eye on it for K26 too.

**Comment by firnsy** [comment]
I've updated to 1.13.8 and pushed to the 26 repos, what exactly is deprecated?

**Comment by DarkEra** [comment]
It was a older version and it stopped working, so ads popped up everywhere, at least on K25. The newer versions contain improvements and (security)fixes.

**Comment by firnsy** [comment]
Right, I'm still not sure what this means "The mozilla-ublock-origin package is deprecated" though.

Deprecated means retired and will be removed soon.

**Comment by firnsy** [comment]
Unless of course you mean it's simply "out of date" and needs to be updated?

**Comment by DarkEra** [comment]
Yeah, that's what i meant. It was a language/translation issues from my end.

**Comment by DarkEra** [comment]
As i already mentioned on IRC, you updated mozilla-ublock-origin package to 1.13.8 but after i re-installed it ublock origin still shows 1.9.16 in Firefox under Extensions. Not sure how that happened.

**Comment by firnsy** [comment]
Hmmm, not sure on that. I didn't have the package, installed it and it shows I have the latest.
If firefox was open when you upgrade, have you tried restarting firefox?
Maybe try a reinstall of the package and make sure firefox is not open when the update occurs.

**Comment by DarkEra** [comment]
Firefox was closed when installing the package. I just reinstalled it and it still shows the 1.9.16 version.

![screenshot_20170808_063247](https://user-images.githubusercontent.com/6264656/29056533-d81fb8a0-7c03-11e7-97f0-f031b7341d58.png)

**Comment by firnsy** [comment]
I'll mark as closed then.
