### ISSUE TITLE
Remove Ksuperkey on Plasma by KDE

### ISSUE THREAD

**Issue by DarkEra** [kororaproject/kp#87]
Ksuperkey can be removed from our KDE Plasma spin since the superkey feature is supported by default from KDE Plasma 5.8 onward. So using the superkey to open the menu works out of the box.

**Comment by jimkp** [comment]
That's good news for KDE but we still need it in Xfce

**Comment by DarkEra** [comment]
No problem, it can stay on our Xfce spin. This issue was opened for KDE Plasma only since ksuperkey conflicts with the default feature, the menu didn't open and close properly. After removing ksuperkey and a log out/in it was solved.

**Comment by firnsy** [comment]
Removed from KDE.
