### ISSUE TITLE
Remove blueman from Cinnamon, MATE and Xfce

### ISSUE THREAD

**Issue by DarkEra** [kororaproject/kp#88]
After building and trying the test iso's of Cinnamon, Mate and Xfce i noticed that the panel has two Bluetooth entries and a error message shows up on the desktop, saying: 

> Failed to apply network settings. You might not be able to connect to the Bluetooth network via this machine.

After removing blueman the conflict is solved and the message doesn't show up anymore.
We spoke about it a while ago on IRC to replace blueman but it seems fedora uses blueberry by default. Thus we need to remove blueman from the three spins mentioned.

**Comment by jimkp** [comment]
removed from Cinnamon, Mate and Xfce

**Comment by DarkEra** [comment]
All seems ok now, closing the issue.
