### ISSUE TITLE
Remove yumex-dnf

### ISSUE THREAD

**Issue by DarkEra** [kororaproject/kp#90]
yumex-dnf still seems to be included on all spins we ship, so we need to remove it since it's developer decided to drop it.

**Comment by jimkp** [comment]
Removed from korora-common-packages

**Comment by jimkp** [comment]
Also remove from Cinnamon, Mate and Xfce

**Comment by DarkEra** [comment]
Built a new Xfce iso today, Yumex is still showing. Probably because the Fedora Xfce spin ships it...?

**Comment by jimkp** [comment]
I excluded it on Xfce. We need to check other desktops too.

**Comment by DarkEra** [comment]
I had a new build of the MATE iso before you excluded it and it didn't have yumex-dnf included. Fedora MATE is one spin that ships dnfdragora and dnfdragora-gui by default so it is included on our spin to.

I'll fire up a new build of Cinnamon to check with what it comes

**Comment by DarkEra** [comment]
Cinnamon and Xfce are fine now, except on the Xfce side of thing we need to remove the yumex-dnf icon from the dock/panel and include dnfdragora since both Cinnamon and MATE seem to ship it.

**Comment by jimkp** [comment]
The settings package for Xfce and Mate will need to be updated. Other changes are need to Xfce settings too as covered in the Xfce issue
