### ISSUE TITLE
update Numix Icons

### ISSUE THREAD

**Issue by jimkp** [kororaproject/kp#92]
~~A new version of the Numix Circle Icon theme was released a few days ago - https://github.com/numixproject/numix-icon-theme-circle/releases/tag/17-08-03~~

Drop the package from the repos and use the one from Fedora

**Comment by DarkEra** [comment]
I don't think it's needed to update since Fedora has the Numix icon set in their repo's. Just like with the Arc Theme we can drop them i guess and use the Fedora packages?

**Comment by jimkp** [comment]
agreed.

Shall I close this or change it to "dump Numix from repo"?

**Comment by DarkEra** [comment]
Change it. Once we dropped it we can close the issue.

**Comment by jimkp** [comment]
> Change it. Once we dropped it we can close the issue.

Done

**Comment by jimkp** [comment]
done so closing
